version: '3.8'

services:
    web:
        image: nginx:latest
        ports:
            - 18080:80
        volumes:
            - ./api:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    app:
        build: ./docker
        volumes:
            - ./api:/var/www/html
        depends_on:
            - db
            - smtp4dev

    # node:
    #     build: ./docker/node
    #     ports:
    #         - '8090:8080'
    #     volumes:
    #         - ./client:/var/www/html

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myapp
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - 13306:3306
        restart: always

    smtp4dev:
        image: rnwood/smtp4dev:linux-amd64-v3
        ports:
            - '3000:80'